#ifndef IC_LIB_FLASH_MAP_H_
#define IC_LIB_FLASH_MAP_H_

//internal flash map
#define INT_FLASH_SIZE						0x40000

#define INT_FLASH_SD_BASE					0x00000
#define INT_FLASH_SD_SIZE					0x17000 //92kB

#define INT_FLASH_APP_BASE					0x17000
#define INT_FLASH_APP_SIZE					0x19000 //100kB

#define INT_FLASH_DFU_BASE					0x30000
#define INT_FLASH_DFU_SIZE					0x08000 //32kB

#define INT_FLASH_FREE_BASE					0x38000
#define INT_FLASH_FREE_SIZE					0x05000 //20kB
#define INT_FLASH_SERIAL_HEADER				INT_FLASH_FREE_BASE

#define INT_FLASH_BOOT_BASE					0x3D000
#define INT_FLASH_BOOT_SIZE					0x03000 //12kB

//external flash map
#define EXT_FLASH_BLOCK_SIZE				0x10000
#define EXT_FLASH_SECTOR_SIZE				0x01000
#define EXT_FLASH_PAGE_SIZE					0x00100

#define EXT_FLASH_BACKUP_SD_BASE			0x00000
#define EXT_FLASH_BACKUP_SD_LEN_BYTES		0x17000	//92kB
#define EXT_FLASH_BACKUP_SD_LEN_SECTORS		23

#define EXT_FLASH_BACKUP_APP_BASE			0x17000
#define EXT_FLASH_BACKUP_APP_LEN_BYTES		0x19000	//100kB
#define EXT_FLASH_BACKUP_APP_LEN_SECTORS	25

#define EXT_FLASH_BACKUP_DFU_BASE			0x30000
#define EXT_FLASH_BACKUP_DFU_LEN_BYTES		0x08000	//32kB
#define EXT_FLASH_BACKUP_DFU_LEN_SECTORS 	8

#define EXT_FLASH_BACKUP_RESV_BASE			0x38000
#define EXT_FLASH_BACKUP_RESV_LEN_BYTES		0x05000	//20kB
#define EXT_FLASH_BACKUP_RESV_LEN_SECTORS 	5

#define EXT_FLASH_APP_CONF_BASE				0x3D000
#define EXT_FLASH_APP_CONF_LEN_BYTES		0x02000	//8kB
#define EXT_FLASH_APP_CONF_LEN_SECTORS		2

#define EXT_FLASH_SD_HEADER					EXT_FLASH_APP_CONF_BASE
#define EXT_FLASH_APP_HEADER				EXT_FLASH_APP_CONF_BASE	+ 16
#define EXT_FLASH_DFU_HEADER				EXT_FLASH_APP_CONF_BASE	+ 32

#define EXT_FLASH_HEADER_BASE				0x3F000
#define EXT_FLASH_HEADER_LEN_BYTES			0x01000	//4kB
#define EXT_FLASH_HEADER_LEN_SECTORS		1

#define EXT_FLASH_DFU_BUFF_BASE				0x40000
#define EXT_FLASH_DFU_BUFF_LEN_BYTES		0x20000	//128kB
#define EXT_FLASH_DFU_BUFF_LEN_BLOCKS		2

#define EXT_FLASH_NEUROON_DEV_DATA			0x40000

#define EXT_FLASH_DATA_BUFF_BASE			0x100000
#define EXT_FLASH_DATA_BUFF_LEN_BYTES		0x1F00000
#define EXT_FLASH_DATA_BUFF_LEN_BLOCKS		0x1F0

//APP TYPES
#define HEADER_APP_TYPE_SD					0
#define HEADER_APP_TYPE_NEUROON				1
#define HEADER_APP_TYPE_DFU					2

//GPREGRET APPS ID
#define GPREGRET_DFU_ID						1
#define GPREGRET_NEUROON_ID					2
#define GPREGRET_NEUROON_DEV_ID				3
#define GPREGRET_APPS_ID_POS				4
#define GPREGRET_DFU_START_CMD				0x80

#endif /*IC_LIB_FLASH_MAP_H_*/
